# Generated by Django 4.2.8 on 2023-12-21 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.UUID('8d1134c5-56ac-405b-8c7a-4091a7a88a9b'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.UUID('e40b3e30-db21-4b2d-912b-ab66c3334ac6'), editable=False, unique=True),
        ),
    ]
