# Generated by Django 4.2.8 on 2023-12-21 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_uuid_alter_sector_sector_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.ManyToManyField(blank=True, to='courses.comment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, to='courses.coursesection'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.UUID('149d23c7-2cff-4d53-89b7-a054901a1b3b'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='courses.episode'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.UUID('69a1fb93-10ea-4f8c-8793-0ba902b2d2c7'), editable=False, unique=True),
        ),
    ]
