# Generated by Django 4.2.8 on 2023-12-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_course_uuid_alter_sector_sector_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_section',
            new_name='course_sections',
        ),
    ]
