# Generated by Django 4.2.8 on 2023-12-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_course_section_course_course_sections'),
        ('users', '0002_remove_user_is_staff_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
